# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20161123_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('G', 'g'), ('K', 'kg'), ('S', 'skje')], max_length=2),
        ),
    ]
