# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('F', 'Fisk'), ('K', 'Kylling'), ('S', 'Svin')], max_length=1),
        ),
    ]
