# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161113_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(unique=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('cost', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'ordering': ['-end_date'],
                'get_latest_by': 'end_date',
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('eaten', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe')),
            ],
            options={
                'ordering': ['plan', 'day'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='planitem',
            unique_together=set([('plan', 'day')]),
        ),
    ]
