# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161114_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planitem', related_query_name='planitems', to='core.Recipe'),
        ),
    ]
