# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161114_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planitems', related_query_name='planitem', to='core.Plan'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe'),
        ),
    ]
